name = "jarr"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "134.209.23.180"
UUID = "0612d9ed-2bff-489f-a995-3ff7ed119476"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
