name = "herutama"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "e068e39a-6fb0-45f9-a60f-a1549e6e7a1e"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
